<?php

namespace Grafit\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    
    public function findAll() 
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT c FROM CoreBundle:category c ORDER BY c.name DESC')
                    ->getResult();
    }
    
}
