<?php

namespace Grafit\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InquiryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InquiryRepository extends EntityRepository
{
    public function findAll() 
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT i FROM CoreBundle:inquiry i ORDER BY i.created DESC')
                    ->getResult();
    }
    
    public function findAllWithLimit($limit) 
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT i FROM CoreBundle:inquiry i ORDER BY i.created DESC')
                    ->setMaxResults($limit)
                    ->getResult();
    }
}
