<?php

namespace Grafit\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StoritveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoritveRepository extends EntityRepository
{
    
    public function findAll() 
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT s FROM CoreBundle:storitve s ORDER BY s.created DESC')
                    ->getResult();
    }

    public function findLastTreeStoritve()
    {
    	return $this->getEntityManager()
                    ->createQuery('SELECT s FROM CoreBundle:storitve s ORDER BY s.created DESC')
                    ->setMaxResults(3)
                    ->getResult();
    }
    
}
